============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
django: settings: contact_app.settings (from ini)
rootdir: /home/sachinvd/Documents/nashtech/CICD-examples, configfile: pytest.ini
plugins: django-4.4.0, Faker-9.8.2
collected 3 items

app/test_file.py::test_contact_create FAILED                             [ 33%]
app/test_file.py::test_view PASSED                                       [ 66%]
app/test_file.py::test_url PASSED                                        [100%]

=================================== FAILURES ===================================
_____________________________ test_contact_create ______________________________

    @pytest.mark.django_db
    def test_contact_create():
        # Create dummy data
        contact = Contact.objects.create(full_name="Someone", phone_number="7XXXXXXXXX",)
        # Assert the dummy data saved as expected
>       assert contact.full_name=="SomeRandom"
E       AssertionError: assert 'Someone' == 'SomeRandom'
E         - SomeRandom
E         + Someone

app/test_file.py:12: AssertionError
---------------------------- Captured stderr setup -----------------------------
Creating test database for alias 'default'...
=========================== short test summary info ============================
FAILED app/test_file.py::test_contact_create - AssertionError: assert 'Someon...
========================= 1 failed, 2 passed in 0.19s ==========================
